---
- name: 110-grafana-instance | Install the Grafana instance
  kubernetes.core.k8s:
    state: present
    template: "grafana.yaml.j2"

- name: 110-grafana-instance | Wait for Grafana instance to deploy
  kubernetes.core.k8s_info:
    kind: Deployment
    namespace: "{{ prometheus_namespace }}"
    name: grafana-deployment
    wait: true
    wait_condition:
      type: Available
      status: true
...
