---
- name: 20-install-prometheus-operator | Create the prometheus-operator namespace
  kubernetes.core.k8s:
    name: "{{ prometheus_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: 20-install-prometheus-operator | Install Prometheus Operator
  kubernetes.core.k8s:
    state: present
    template: "prometheus-operator.yaml.j2"

- name: 20-install-prometheus-operator | Wait for Prometheus Operator to deploy
  kubernetes.core.k8s_info:
    kind: Deployment
    namespace: "{{ prometheus_namespace }}"
    name: prometheus-operator
    wait: true
    wait_condition:
      type: Available
      status: true
...
