---
- name: 90-install-grafana-operator | Install Grafana Operator
  kubernetes.core.k8s:
    state: present
    template: "grafana-operator.yaml.j2"

- name: 90-install-grafana-operator | Wait for Grafana Operator to deploy
  kubernetes.core.k8s_info:
    kind: Deployment
    namespace: "{{ prometheus_namespace }}"
    name: grafana-operator-controller-manager
    wait: true
    wait_condition:
      type: Available
      status: true
...
